# Generated by Django 3.2.6 on 2021-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='image_profil',
            field=models.ImageField(blank=True, upload_to='profil_photo/'),
        ),
    ]
