# Generated by Django 3.2.6 on 2021-08-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre_formation',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='greenform_app.membre')),
                ('nom', models.CharField(max_length=30)),
                ('responsable', models.CharField(max_length=30)),
            ],
            bases=('greenform_app.membre',),
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='greenform_app.membre')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=100)),
                ('num_tel', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('Bénévole', 'Bénévole'), ('Donateur', 'Donateur'), ('Autre', 'Autre')], max_length=30)),
            ],
            bases=('greenform_app.membre',),
        ),
        migrations.AlterField(
            model_name='membre',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
