# Generated by Django 3.2.6 on 2021-08-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0002_auto_20210810_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre_formation',
            old_name='nom',
            new_name='nom_du_centre',
        ),
        migrations.AlterModelTable(
            name='centre_formation',
            table='Centre de formation',
        ),
        migrations.AlterModelTable(
            name='personne',
            table='Personne lambda',
        ),
    ]
