# Generated by Django 3.2.6 on 2021-08-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0003_auto_20210810_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.IntegerField()),
                ('type_etablissement', models.CharField(choices=[('Ecole', 'Ecole'), ('Université', 'Université'), ('Ecole de formation', 'Ecole de formation'), ('Centre', 'Centre')], max_length=30)),
                ('representant', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.IntegerField()),
                ('num_tel', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='centre_formation',
            name='code_postal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='code_postal',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenform_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateField()),
                ('id_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenform_app.abonnement')),
                ('id_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenform_app.inscription')),
            ],
            options={
                'db_table': 'Adhérant',
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('id_etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenform_app.etablissement')),
                ('id_partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenform_app.partenaire')),
                ('membres', models.ManyToManyField(related_name='Participation', to='greenform_app.Membre')),
            ],
        ),
    ]
