# Generated by Django 3.2.6 on 2021-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0004_auto_20210810_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='code_postal',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
