# Generated by Django 3.2.6 on 2021-08-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0004_abonnement_type_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='numero',
        ),
    ]
