# Generated by Django 3.2.6 on 2021-08-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0005_alter_personne_code_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='type',
        ),
        migrations.AddField(
            model_name='membre',
            name='type',
            field=models.CharField(choices=[('Bénévole', 'Bénévole'), ('Donateur', 'Donateur'), ('Autre', 'Autre')], max_length=30, null=True),
        ),
    ]
