# Generated by Django 3.2.6 on 2021-08-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0005_remove_abonnement_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='id_inscription',
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
