# Generated by Django 3.2.6 on 2021-08-29 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0006_auto_20210829_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='id_membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='date_abonnement',
            field=models.DateField(auto_now_add=True),
        ),
    ]
