# Generated by Django 3.2.6 on 2021-08-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0007_auto_20210829_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='id_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenform_app.membre'),
        ),
    ]
