# Generated by Django 3.2.6 on 2021-08-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0007_auto_20210815_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='user_permissions',
        ),
    ]
