# Generated by Django 3.2.6 on 2021-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0008_alter_adherent_id_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='date_abonnement',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
