# Generated by Django 3.2.6 on 2021-08-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0008_auto_20210815_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
