# Generated by Django 3.2.6 on 2021-08-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0002_alter_activite_membres'),
        ('greenform_app', '0009_alter_adherent_date_abonnement'),
    ]

    operations = [
    ]
