# Generated by Django 3.2.6 on 2021-08-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('greenform_app', '0009_auto_20210815_2320'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='centre_formation',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='membre',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personne',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='membre',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
