# Generated by Django 3.2.6 on 2021-08-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0010_auto_20210816_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='centre_formation',
            name='code_postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
