# Generated by Django 3.2.6 on 2021-08-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0011_auto_20210816_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='last_read',
            field=models.BooleanField(default=False),
        ),
    ]
