# Generated by Django 3.2.6 on 2021-08-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0012_membre_last_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='last_read',
        ),
    ]
