# Generated by Django 3.2.6 on 2021-08-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenform_app', '0013_remove_membre_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
